<?php

return [
    'title' => 'Help',
    'close' => 'Close help',
    'workflow_title' => 'How do these programs work together?',
    'workflow' => 'Import Center brings files and content in. Media Library shows stored originals. Videos, Posts and Community show associated content. Importing and classifying do not publish anything automatically.',
    'navigation_title' => 'Using windows',
    'navigation' => 'You can move, resize and close this help window. Your working window stays open. Search and filters only change the view; they do not delete materials.',
    'pending' => 'The native workspace for this program is not fully implemented yet. An empty area does not mean archived files were deleted. Use Media Library and Import Center for the implemented archive functions.',
    'apps' => [
        'imports' => [
            'Choose one of five methods: computer archive, public link, existing archive, server folder or Google Takeout from server.',
            'Place all ZIP parts or the complete extracted export in the configured private Takeout folder (private/Takeout by default). Select the export and, for ZIPs, the expected part count. Leave the original export unchanged; the importer copies the required files using new SHA-256 names.',
            'CSV provides content IDs, original text and links; the optional HTML report checks the file inventory. Report ZIPs are excluded. Videos, posts, images, polls, quizzes, comments, live chat and playlists are processed together. Channels, subscriptions, history and shopping data are under Private account data (Takeout).',
            'Importing does not publish content or trigger automatic AI processing. The saved duration classification rule is applied without AI. Free video, audio and image files are stored under public/media and served directly by our server; private account data stays protected.',
            'Detailed results show added, enriched, duplicate, failed and ambiguous objects. Resume skips completed files and metadata; the interrupted ZIP entry may be extracted again. Originals remain intact.',
            'Reset old catalog removes old YouTube records and image-generated posts from the active view, not originals. Restore never overwrites new content. Check local videos verifies files/format; browser verification separately confirms actual playback.',
        ],
        'media' => ['Library starts with complete content: original title/text, related images/videos, polls and comments. Files opens a separate thumbnail gallery of originals. Individual images are not automatically created posts.', 'Import opens Import Center. Existing archives registers previous uploads and public YouTube archives without redownloading. Use the dedicated Takeout method for your private Google export.', 'Check local videos opens a visible per-video report: missing files, format problems or available originals. Run browser verification afterwards to confirm actual local playback. No AI costs.', 'AI sorts existing content and classifies files without inventing a post from a single file. It does not listen to audio or analyze video tracks. Takeout does not automatically trigger AI processing.'],
        'videos' => ['Complete imported video content and Shorts: original title, description, video file, cover and comments. Preview and playback use our server only.', 'Playlists are local saved lists, not synchronized live with YouTube. Open local content shows the complete record. Edit membership, order and text locally.', 'Check local videos checks every registered video. Browser verification tests range requests, seeking and actual playback. Missing originals are shown explicitly, not replaced by YouTube.'],
        'posts' => ['A post is its imported original text with related images, polls and comments. A single image with an AI description is not an original post.', 'Attachments come from our private archive. Edit text, title, tags and status locally. No YouTube playback or external navigation buttons; importing does not automatically publish.'],
        'community' => ['This area shows imported polls and comments. Belongs to identifies the original post or video when that relationship is present in the export.', 'A stored comment is an archive copy. This interface does not send replies to external services. Importing does not publish anything.'],
        'live-studio' => ['Save the livestream with a title and schedule first. Its date then appears in Calendar. “Publish on the website” exposes the public page; “enable for shared OBS ingest” selects the event that receives the incoming signal.', 'For OBS, copy the displayed OBS address and use it as the stream destination. The server needs the one-time protected Live configuration. If no address is shown, an authorized person must check the Live server, certificate and network access.', 'To broadcast without OBS, choose “Broadcast directly in the browser”, grant camera and microphone access, select the devices and prepare the local preview first. Only “Start stream” sends media after confirmation. Camera or microphone access can be restored in the browser’s site permissions.'],
        'settings' => ['Tabs separate desktop appearance, AI, social media, publishing, integrations, permissions and system settings. Save changes explicitly.', 'AI classification requires enabled AI, an OpenAI model and an API key. Automatic classification can be disabled. Social configuration alone does not establish OAuth access or publishing.', 'Your personal profile opens from your name in the Start menu and is separate from official project accounts.'],
    ],
];
