import { chromium } from '../../.local/node_modules/playwright/index.mjs';
import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { checkDesktopShortcuts } from './desktop-shortcuts.mjs';
const server=spawn('php',['artisan','serve','--host=127.0.0.1','--port=8791'],{stdio:'pipe',detached:true});
let output='';server.stderr.on('data',b=>output+=b);server.stdout.on('data',b=>output+=b);
let browser;
try {
  let ready=false;
  for(let i=0;i<60;i++){try{const r=await fetch('http://127.0.0.1:8791/login');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}
  assert(ready,output);
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await fs.mkdir('tests/artifacts',{recursive:true});
  await page.goto('http://127.0.0.1:8791/');
  await page.evaluate(()=>document.fonts.ready);
  await page.evaluate(()=>Promise.all([...document.images].map(image=>image.decode())));
  assert.equal(await page.locator('link[rel="icon"]').getAttribute('href'),'/favicon.png');
  assert.equal(await page.locator('.kit-brand img').getAttribute('src'),'/assets/brand/owner/logo-stacked.png');
  assert.deepEqual(await page.locator('.kit-brand img').evaluate(image=>[image.naturalWidth,image.naturalHeight]),[1448,1086]);
  await page.screenshot({path:'tests/artifacts/home-notice.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'tests/artifacts/home-notice-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:8791/login');
  await page.locator('.kit-brand img').waitFor();
  await page.evaluate(()=>Promise.all([...document.images].map(image=>image.decode())));
  await fs.mkdir('tests/artifacts',{recursive:true});
  await page.screenshot({path:'tests/artifacts/login.png',fullPage:true});
  await page.locator('[name=email]').fill('test@example.com');
  await page.locator('[name=password]').fill('kurz5');
  await page.locator('button[type=submit], form button').click();
  await page.waitForURL('**/desktop');
  await checkDesktopShortcuts(page, { reenter:async () => {
    await page.locator('[data-start-button]').click();
    await page.locator('.os-start-menu button[type="submit"]').click();
    await page.goto('http://127.0.0.1:8791/login');
    await page.locator('[name=email]').fill('test@example.com');
    await page.locator('[name=password]').fill('kurz5');
    await page.locator('button[type=submit], form button').click();
    await page.waitForURL('**/desktop');
  } });
  const shortcutStorage = await page.locator('[data-desktop]').getAttribute('data-storage-key');
  const savedShortcuts = await page.evaluate(key => localStorage.getItem(`${key}.shortcuts`), shortcutStorage);
  await page.goto('http://127.0.0.1:8791/desktop/settings');
  await page.locator('[name=desktop_icon_set]').selectOption('standard');
  await page.locator('[name=desktop_wallpaper]').selectOption('navy');
  await page.locator('[name=desktop_accent]').selectOption('sky');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.goto('http://127.0.0.1:8791/desktop');
  assert.equal(await page.locator('.os-start-menu [data-open-app="videos"]').getAttribute('data-app-icon'),'/assets/brand/owner/desktop/standard/Videos.png');
  assert.equal(await page.locator('[data-desktop]').getAttribute('data-wallpaper'),'navy');
  assert.equal(await page.locator('[data-desktop]').getAttribute('data-accent'),'sky');
  assert.equal(await page.evaluate(key => localStorage.getItem(`${key}.shortcuts`), shortcutStorage),savedShortcuts);
  await page.goto('http://127.0.0.1:8791/desktop/settings');
  await page.locator('[name=desktop_icon_set]').selectOption('manna');
  await page.locator('[name=desktop_wallpaper]').selectOption('mountains');
  await page.locator('[name=desktop_accent]').selectOption('gold');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.goto('http://127.0.0.1:8791/desktop');
  assert.equal(await page.locator('.os-start-menu [data-open-app="videos"]').getAttribute('data-app-icon'),'/assets/brand/owner/desktop/manna/Videos.png');
  await page.setViewportSize({width:1440,height:1000});
  await fs.mkdir('tests/artifacts',{recursive:true});
  await page.screenshot({path:'tests/artifacts/desktop.png',fullPage:true});
  await page.locator('[data-open-app="videos"]').first().click();
  const desktopTitle=await page.locator('.os-window[data-app-id="videos"] [data-drag-handle]').boundingBox();
  await page.mouse.move(desktopTitle.x+100,desktopTitle.y+20);
  await page.mouse.down();await page.mouse.move(720,8,{steps:8});await page.mouse.up();
  await page.locator('[data-layout="four"][data-zone="0"]').click();
  await page.locator('[data-start-button]').click();
  await page.locator('.os-start-menu [data-open-app="tasks"]').click();
  const videoWindow=page.locator('.os-window[data-app-id="videos"]');
  await videoWindow.locator('[data-window-action="pin"]').click();
  const south=await videoWindow.locator('[data-resize="s"]').boundingBox();
  await page.mouse.move(south.x+south.width/2,south.y+3);
  await page.mouse.down();await page.mouse.move(south.x+south.width/2,940,{steps:8});await page.mouse.up();
  let movedTitle=await videoWindow.locator('[data-drag-handle]').boundingBox();
  await page.mouse.move(movedTitle.x+100,movedTitle.y+20);
  await page.mouse.down();await page.mouse.move(movedTitle.x+125,movedTitle.y+30,{steps:3});await page.mouse.up();
  assert.equal(await videoWindow.getAttribute('data-snap-layout'),null,'Small manual move forced the window back into the layout');
  movedTitle=await videoWindow.locator('[data-drag-handle]').boundingBox();
  await page.mouse.move(movedTitle.x+100,movedTitle.y+20);
  await page.mouse.down();await page.mouse.move(200,700,{steps:8});await page.mouse.up();
  assert.equal(await videoWindow.getAttribute('data-snap-zones'),'0,2','Adjacent vertical zones were not merged');
  assert.equal(await videoWindow.getAttribute('data-pinned'),'true','Pinned state changed during Snap');
  assert.equal(await page.locator('.os-snap-preview').isVisible(),false,'Snap preview remained after drop');
  await page.locator('[data-start-button]').click();
  await page.locator('.os-start-menu [data-open-app="images"]').click();
  assert.equal(await page.locator('.os-window[data-app-id="images"]').getAttribute('data-snap-zone'),'3','Merged region did not reserve both cells');
  await page.reload();
  assert.equal(await page.locator('.os-window').count(),3,'Desktop windows were not restored');
  assert.equal(await videoWindow.getAttribute('data-snap-zones'),'0,2','Merged region was not restored');
  assert.equal(await page.locator('.os-snap-preview').isVisible(),false,'Snap preview returned after reload');
  for(const appId of ['videos','tasks','images'])await page.locator(`.os-window[data-app-id="${appId}"] [data-window-action="close"]`).click();
  const emptyDesktopState=await page.evaluate(()=>{const root=document.querySelector('[data-desktop]');return JSON.parse(localStorage.getItem(root.dataset.storageKey));});
  assert.equal(emptyDesktopState.layoutId,null,'Layout remained active after closing the last window');
  await page.locator('[data-open-app="videos"]').first().click();
  assert.equal(await page.locator('.os-window[data-app-id="videos"]').getAttribute('data-snap-layout'),null,'Reset layout was reused');
  await page.locator('[data-close-all]').click();await page.reload();
  assert.equal(await page.locator('.os-window').count(),0,'Desktop windows returned after close all');
  await page.goto('http://127.0.0.1:8791/desktop/media');
  await page.locator('[name=file]').setInputFiles({name:'Hoffnung.txt',mimeType:'text/plain',buffer:Buffer.from('Hoffnung für heute')});
  await page.locator('.upload-form button').click();
  await page.waitForURL(/\/desktop\/media\/.+/);
  assert.match(await page.locator('h1').innerText(),/Hoffnung/);
  await page.locator('[name=title]').fill('Notizen für Sonntag');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  assert.match(await page.locator('h1').innerText(),/Notizen/);
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Original herunterladen'}).click()]);
  assert.equal(download.suggestedFilename(),'Hoffnung.txt');
  await page.goto('http://127.0.0.1:8791/desktop/media');
  await page.screenshot({path:'tests/artifacts/library.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');
  await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');
  await page.keyboard.press('Escape');
  await page.screenshot({path:'tests/artifacts/mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Browser: desktop persistence, upload, rename, download, responsive navigation OK');
} finally {await browser?.close();try{process.kill(-server.pid,'SIGTERM');}catch{}server.stdout.destroy();server.stderr.destroy();server.unref();}
