<?php

return [
    'title' => 'Hilfe',
    'close' => 'Hilfe schließen',
    'workflow_title' => 'Wie arbeiten die Programme zusammen?',
    'workflow' => 'Import Center holt Dateien und Inhalte herein. Media Library zeigt die gespeicherten Originale. Videos, Beiträge und Community zeigen die zugehörigen Inhalte. Importieren und Sortieren veröffentlicht nichts automatisch.',
    'navigation_title' => 'Fenster bedienen',
    'navigation' => 'Sie können dieses Hilfefenster verschieben, vergrößern und schließen. Ihr Arbeitsfenster bleibt geöffnet. Suche und Filter schränken nur die Ansicht ein; sie löschen keine Materialien.',
    'pending' => 'Für dieses Programm ist der native Arbeitsbereich noch nicht vollständig umgesetzt. Ein leerer Bereich bedeutet nicht, dass vorhandene Archivdateien gelöscht wurden. Verwenden Sie Media Library und Import Center für bereits implementierte Archivfunktionen.',
    'apps' => [
        'imports' => ['Wählen Sie zuerst einen von vier Wegen: Archiv vom Computer, öffentlicher Link, bereits gespeichertes Archiv oder freigegebener Server-Ordner. Nur die dafür notwendigen Felder werden angezeigt.', 'Vorhandene Archive registriert die bisherigen Uploads oder den gesammelten YouTube-Archivbestand. Ordner auf dem Server zeigt ausschließlich den freigegebenen Import-Bereich. Klicken Sie einen Ordner an, um seinen Inhalt zu sehen; wählen Sie ihn anschließend ausdrücklich zum Import aus.', 'Ein ZIP/TAR wird zuerst hochgeladen und dann im Hintergrund gelesen. Unterbrochene Uploads können durch erneutes Auswählen derselben Datei fortgesetzt werden. Unbekannte Exportformate werden als Dateien gespeichert, aber nicht automatisch als Beiträge verstanden.', 'Im Import-Protokoll sehen Sie neu registrierte und übersprungene Einträge. Ein übersprungener Eintrag kann bereits vorhanden sein. Fehler oder ein Teilimport werden nicht als vollständiger Erfolg behandelt.'],
        'media' => ['Hier sehen Sie lokale Archivdateien. Ein Klick auf eine Datei zeigt Vorschau, Details und Download. Die Schaltfläche Beiträge & Metadaten wechselt zur Inhaltsansicht; sie enthält auch Texte ohne eigene Videodatei.', 'Vorhandene Archive einlesen macht bisherige Uploads und YouTube-Originale sichtbar. Es lädt sie nicht erneut von YouTube herunter. Für neue Links und ZIP/TAR verwenden Sie Import Center.', 'Unsortiert bedeutet noch nicht eingeordnet. Tags und Zielbereich können Sie manuell ändern. Eine Zuordnung zu Videos oder Beiträge verwendet denselben Originalbestand; sie veröffentlicht nichts.', 'KI nutzt vorhandene Texte, Beschreibungen, Metadaten und unterstützte kleine Bilder. Sie hört keine Audioaufnahmen an und analysiert keine Videospuren. Bei zu wenig Information bleibt eine Prüfung erforderlich.'],
        'videos' => ['Die Liste zeigt lokal gespeicherte Video-Inhalte und Shorts. Eine gespeicherte Beschreibung oder ein Vorschaubild bedeutet nicht, dass auch die Videodatei vorhanden ist. Im Detail sehen Sie ausdrücklich, ob ein Video-Original verfügbar ist.', 'Playlist zeigt die lokal importierte Reihenfolge einer ursprünglichen Playlist. Sie ist nicht live mit YouTube synchronisiert. Lokalen Inhalt öffnen zeigt unsere gespeicherten Informationen; Auf YouTube öffnen führt ausdrücklich zur externen Website.', 'Fehlende Positionen oder Dateien bleiben sichtbar. Sie können später durch einen weiteren Archiv- oder Linkimport ergänzt werden.'],
        'posts' => ['Beiträge sind gespeicherte Texte, ggf. mit Bildern und weiteren Dateien. Originaltext ist der importierte Beitrag, nicht eine automatisch veröffentlichte Website-Seite.', 'Eine externe Original-Schaltfläche führt zum ursprünglichen Dienst. Zugehörige Dateien stammen aus unserem privaten Archiv. Titel, Text, Tags und Status können im Detail bearbeitet werden.'],
        'community' => ['Hier finden Sie importierte Umfragen und Kommentare. Gehört zu bezeichnet den ursprünglichen Beitrag oder das Video, sofern der Export diese Verbindung enthält.', 'Ein gespeicherter Kommentar ist eine Archivkopie. Die Oberfläche sendet keine Antworten an YouTube oder andere Dienste. Importieren ist keine Veröffentlichung.'],
        'settings' => ['Die Registerkarten trennen Desktop-Gestaltung, KI, Social Media, Publishing, Integrationen, Benutzerrechte und System. Änderungen müssen gespeichert werden.', 'Die KI-Einordnung benötigt aktivierte KI, ein OpenAI-Modell und einen API-Schlüssel. Automatische Einordnung kann ausgeschaltet werden. Social-Media-Konfiguration allein bedeutet noch keine funktionierende OAuth-Anmeldung oder Veröffentlichung.', 'Ihr persönliches Profil wird über Ihren Namen im Startmenü geöffnet. Es ist von offiziellen Projektkonten getrennt.'],
    ],
];
