<?php

return [
    'title' => 'Hilfe',
    'close' => 'Hilfe schließen',
    'workflow_title' => 'Wie arbeiten die Programme zusammen?',
    'workflow' => 'Import Center holt Dateien und Inhalte herein. Media Library zeigt die gespeicherten Originale. Videos, Beiträge und Community zeigen die zugehörigen Inhalte. Importieren und Sortieren veröffentlicht nichts automatisch.',
    'navigation_title' => 'Fenster bedienen',
    'navigation' => 'Sie können dieses Hilfefenster verschieben, vergrößern und schließen. Ihr Arbeitsfenster bleibt geöffnet. Suche und Filter schränken nur die Ansicht ein; sie löschen keine Materialien.',
    'pending' => 'Für dieses Programm ist der native Arbeitsbereich noch nicht vollständig umgesetzt. Ein leerer Bereich bedeutet nicht, dass vorhandene Archivdateien gelöscht wurden. Verwenden Sie Media Library und Import Center für bereits implementierte Archivfunktionen.',
    'apps' => [
        'imports' => ['Wählen Sie zuerst einen von fünf Wegen: Archiv vom Computer, öffentlicher Link, bestehendes Archiv, Server-Ordner oder Google Takeout vom Server. Nur notwendige Felder werden gezeigt.', 'Für Takeout alle ZIP-Teile in private/youtube_zip_alle ablegen, Export und Gesamtzahl auswählen. Bericht-ZIPs werden nicht als Inhalt importiert. Bilder, Texte, Umfragen und Kommentare werden zum ursprünglichen Beitrag verbunden; Videos spielen ausschließlich lokal.', 'Ergebnis im Detail zeigt neue, ergänzte, vorhandene, fehlgeschlagene und unklare Objekte. Fortsetzen überspringt abgeschlossene Dateien und Metadaten. Der laufende ZIP-Eintrag kann erneut ausgepackt werden; gespeicherte Originale bleiben erhalten.', 'Alten Katalog zurücksetzen entfernt alte YouTube-Datensätze und aus Einzelbildern erzeugte Beiträge aus der aktiven Ansicht, nicht die Originale. Wiederherstellung überschreibt keine neu importierten Inhalte. Lokale Videos prüfen kontrolliert Dateien und Format; Alle im Browser prüfen bestätigt tatsächliche Wiedergabe separat.'],
        'media' => ['Die Bibliothek beginnt mit vollständigen Inhalten: Titel, Originaltext, zugehörigen Bildern/Videos, Umfragen und Kommentaren. Dateien wechselt zur separaten Kachelansicht der Originale, ähnlich einem Computer-Ordner; einzelne Bilder sind keine automatisch erzeugten Beiträge.', 'Importieren öffnet Import Center. Vorhandene Archive einlesen registriert frühere Uploads und öffentliche YouTube-Archive, ohne erneut herunterzuladen. Für den privaten Google-Export den eigenen Takeout-Weg benutzen.', 'Lokale Videos prüfen öffnet ein sichtbares Prüfprotokoll: fehlende Datei, Formatfehler oder verfügbarer Originalbestand. Die tatsächliche Wiedergabe muss anschließend in diesem Browser geprüft werden. Keine KI-Kosten.', 'KI sortiert bestehende Inhalte und klassifiziert Dateien, erzeugt aber keinen Beitrag aus einer einzelnen Datei. Sie hört keine Audioaufnahmen an und analysiert keine Videospuren. Neue Takeout-Imports starten keine automatische KI-Verarbeitung.'],
        'videos' => ['Hier sehen Sie vollständige lokal importierte Video-Inhalte und Shorts: Originaltitel, Beschreibung, verbundene Videodatei, Cover und Kommentare. Vorschau und Wiedergabe nutzen nur unseren Server.', 'Playlists sind lokal gespeicherte Listen, nicht live mit YouTube synchronisiert. Lokalen Inhalt öffnen zeigt den vollständigen Inhalt; Reihenfolge, Titel und Mitgliedschaft können lokal bearbeitet werden.', 'Lokale Videos prüfen kontrolliert alle registrierten Videos. Alle im Browser prüfen testet HTTP-Teilabruf, Vorspulen und tatsächliche Wiedergabe. Fehlende Dateien bleiben ausdrücklich sichtbar und werden nicht durch YouTube ersetzt.'],
        'posts' => ['Ein Beitrag besteht aus dem importierten Originaltext mit zugehörigen Bildern, Umfragen und Kommentaren. Eine einzelne Datei mit KI-Bildbeschreibung ist kein ursprünglicher Beitrag.', 'Zugehörige Dateien kommen aus unserem privaten Archiv. Titel, Text, Tags und Status können lokal bearbeitet werden. Es gibt keine YouTube-Wiedergabe oder externe Navigations-Schaltfläche; der Import veröffentlicht nichts automatisch.'],
        'community' => ['Hier finden Sie importierte Umfragen und Kommentare. Gehört zu bezeichnet den ursprünglichen Beitrag oder das Video, sofern der Export diese Verbindung enthält.', 'Ein gespeicherter Kommentar ist eine Archivkopie. Die Oberfläche sendet keine Antworten an YouTube oder andere Dienste. Importieren ist keine Veröffentlichung.'],
        'settings' => ['Die Registerkarten trennen Desktop-Gestaltung, KI, Social Media, Publishing, Integrationen, Benutzerrechte und System. Änderungen müssen gespeichert werden.', 'Die KI-Einordnung benötigt aktivierte KI, ein OpenAI-Modell und einen API-Schlüssel. Automatische Einordnung kann ausgeschaltet werden. Social-Media-Konfiguration allein bedeutet noch keine funktionierende OAuth-Anmeldung oder Veröffentlichung.', 'Ihr persönliches Profil wird über Ihren Namen im Startmenü geöffnet. Es ist von offiziellen Projektkonten getrennt.'],
    ],
];
