@extends('layouts.app')
@section('title',__('ui.import_center'))
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ __('ui.contents') }}</p><h1>{{ __('ui.import_center') }}</h1><p class="muted">{{ __('ui.import_intro') }}</p></div></div>
<div class="project-grid">@foreach(['intake','youtube'] as $source)<section class="panel"><h2>{{ __('ui.import_'.$source) }}</h2><p class="muted">{{ __('ui.import_'.$source.'_hint') }}</p><form method="post" action="{{ route('imports.store') }}">@csrf<input type="hidden" name="source" value="{{ $source }}"><button class="button">{{ __('ui.import_start') }}</button></form></section>@endforeach</div>
<section class="panel table-wrap"><h2>{{ __('ui.import_runs') }}</h2><table><thead><tr><th>{{ __('ui.source') }}</th><th>{{ __('ui.status') }}</th><th>{{ __('ui.imported') }}</th><th>{{ __('ui.skipped') }}</th><th>{{ __('ui.date') }}</th></tr></thead><tbody>@forelse($runs as $run)<tr><td>{{ __('ui.import_'.$run->source) }}</td><td>{{ __('ui.run_'.$run->status) }}@if($run->notes)<details><summary>{{ __('ui.notes') }}</summary>@foreach($run->notes as $note)<p>{{ $note }}</p>@endforeach</details>@endif</td><td>{{ $run->imported }}</td><td>{{ $run->skipped }}</td><td>{{ $run->created_at->timezone(config('platform.timezone'))->format('d.m.Y H:i') }}</td></tr>@empty<tr><td colspan="5">{{ __('ui.no_imports') }}</td></tr>@endforelse</tbody></table></section>
@if($collections->isNotEmpty())<section class="panel"><h2>{{ __('ui.playlists') }}</h2><div class="project-grid">@foreach($collections as $collection)<a href="{{ route('collections.show',$collection) }}">{{ $collection->title }} <small>({{ $collection->items_count }})</small></a>@endforeach</div></section>@endif
<section class="panel table-wrap"><h2>{{ __('ui.import_review') }}</h2><nav class="tabs"><a href="{{ route('imports.index') }}">{{ __('ui.view_all') }}</a>@foreach(['video','short','post'] as $kind)<a href="{{ route('imports.index',['kind'=>$kind]) }}">{{ __('ui.source_'.$kind) }}</a>@endforeach</nav><table><thead><tr><th>{{ __('ui.title') }}</th><th>{{ __('ui.type') }}</th><th>{{ __('ui.status') }}</th></tr></thead><tbody>@forelse($records as $record)<tr><td><a href="{{ route('imports.show',$record) }}">{{ $record->title }}</a></td><td>{{ __('ui.source_'.$record->kind) }}</td><td>{{ __('ui.import_review') }}</td></tr>@empty<tr><td colspan="3">{{ __('ui.no_records') }}</td></tr>@endforelse</tbody></table>{{ $records->links() }}</section>
@endsection
