<?php
return [
    'brand' => env('PLATFORM_BRAND', 'Atapin Media'),
    'theme' => env('PLATFORM_THEME', 'manna'),
    'timezone' => env('PLATFORM_TIMEZONE', 'Europe/Berlin'),
    'locales' => ['de', 'en'],
    'media_disk' => env('MEDIA_DISK', 'local'),
    'media_ffprobe_binary' => env('MEDIA_FFPROBE_BINARY', 'ffprobe'),
    'media_upload_max_bytes' => (int) env('MEDIA_UPLOAD_MAX_BYTES', 20 * 1024 * 1024 * 1024),
    'media_upload_max_archive_bytes' => (int) env('MEDIA_UPLOAD_MAX_ARCHIVE_BYTES', 100 * 1024 * 1024 * 1024),
    'media_upload_reserve_free_bytes' => (int) env('MEDIA_UPLOAD_RESERVE_FREE_BYTES', 5 * 1024 * 1024 * 1024),
    'media_upload_max_pending_uploads' => (int) env('MEDIA_UPLOAD_MAX_PENDING_UPLOADS', 10000),
    'intake_root' => env('INTAKE_ROOT', dirname(base_path(), 2).'/private/manna-intake'),
    'youtube_root' => env('YOUTUBE_ROOT', dirname(base_path(), 2).'/private/manna-youtube'),
    'import_inbox_root' => env('IMPORT_INBOX_ROOT', dirname(base_path(), 2).'/private/import-inbox'),
    'takeout_root' => env('TAKEOUT_ROOT', dirname(base_path(), 2).'/private/youtube_zip_alle'),
    'takeout_folder' => env('TAKEOUT_FOLDER', dirname(base_path(), 2).'/private/Takeout'),
    'import_python' => env('IMPORT_PYTHON', dirname(base_path(), 2).'/private/manna-youtube-runtime/bin/python'),
    'import_node' => env('IMPORT_NODE', '/opt/plesk/node/22/bin/node'),
];
